//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace locamerguu
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmplacementSejour
    {
        public int idES { get; set; }
        public int codeEmplacement { get; set; }
        public int idSejour { get; set; }
    
        public virtual Emplacement Emplacement { get; set; }
        public virtual Sejour Sejour { get; set; }
    }
}
