//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace locamerguu
{
    using System;
    using System.Collections.Generic;
    
    public partial class locationOption
    {
        public int idLoc { get; set; }
        public double quantitee { get; set; }
        public double duree { get; set; }
        public int idOption { get; set; }
        public int idSejour { get; set; }
    
        public virtual Option Option { get; set; }
        public virtual Sejour Sejour { get; set; }
    }
}
