//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace locamerguu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocamerGRuEntities : DbContext
    {
        public LocamerGRuEntities()
            : base("name=LocamerGRuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Emplacement> Emplacement { get; set; }
        public virtual DbSet<EmplacementSejour> EmplacementSejour { get; set; }
        public virtual DbSet<locationOption> locationOption { get; set; }
        public virtual DbSet<Option> Option { get; set; }
        public virtual DbSet<Sejour> Sejour { get; set; }
        public virtual DbSet<Tarif> Tarif { get; set; }
        public virtual DbSet<Type> Type { get; set; }
    }
}
